version: "3.7"

volumes:
  rainloop-data: {}

services: 
  rainloop:
    image: docker.pkg.github.com/drdaeman/rainloop-docker/rainloop-php:latest
    build: 
      context: rainloop
    volumes:
      - type: volume
        source: rainloop-data
        target: /var/www/html/data
  nginx:
    image: docker.pkg.github.com/drdaeman/rainloop-docker/rainloop-nginx:latest
    build:
      context: nginx
    ports:
      - target: 80
        published: 8080
